# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kristijan Bambir
tagline: web developer
email: kristijan.bambir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kristijan Bambir is a full stack web developer from Zagreb, Croatia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kristijanbambir.from.hr" # the base hostname & protocol for your site
github_username: kristijanbambir
instagram_username: kristijanbambir
linkedin_username: kristijanbambir
twitter_username: KristijanBambir

# Build settings
markdown: kramdown

safe: true
