application: html5slides
version: 5-5
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
- url: /src
  static_dir: src

- url: /css
  static_dir: css

- url: /disclaimer.html
  static_files: disclaimer.html
  upload: disclaimer.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# Server appropriate mimetype for certain static content.
- url: /(.*\.(appcache|manifest))
  static_files: \1
  mime_type: text/cache-manifest
  upload: (.*\.(appcache|manifest))
  expiration: "0s"

- url: /(.*\.mp4)
  static_files: /\1
  mime_type: video/mp4
  upload: /(.*\.mp4)

- url: /(.*\.webm)
  static_files: /\1
  mime_type: video/webm
  upload: /(.*\.webm)

- url: /(.*\.(ogg|oga))
  static_files: /\1
  mime_type: audio/ogg
  upload: /(.*\.(ogg|oga))

- url: /(.*\.ogv)
  static_files: /\1
  mime_type: video/ogg
  upload: /(.*\.ogv)

- url: /(.*\.mp3)
  static_files: /\1
  mime_type: audio/mpeg
  upload: /(.*\.mp3)

- url: /
  static_files: html5.html
  upload: html5.html

